apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-test-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-test
  template:
    metadata:
      labels:
        app: express-test
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: managedBy
                operator: In
                values:
                - karpenter
              - key: nodepool
                operator: In
                values:
                - express-test
      terminationGracePeriodSeconds: 0
      containers:
        - name: express-test
          image: public.ecr.aws/k3d0y0m9/express-test:1.1.2
          resources:
            requests:
              cpu: "1"
